---
version: 2
jobs:
  lint:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install -qq make
      - run: make flake8

workflows:
  version: 2
  securedrop_workstation_ci:
    jobs:
      - lint
